# Generated by Django 5.2.11 on 2026-02-20 11:46

import django.contrib.auth.validators
from django.db import migrations, models

import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("cvat_id", models.IntegerField(unique=True, verbose_name="CVAT Id")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="Email")),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="Username",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("surname", models.CharField(blank=True, max_length=255, null=True, verbose_name="Отчество")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата последней синхронизации"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Администратор"), ("user", "Пользователь"), ("worker", "Рабочий")],
                        default="user",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                ("has_analytics_access", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
