# Generated by Django 5.2.10 on 2026-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="has_analytics_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последней синхронизации"),
        ),
    ]
