# Generated by Django 5.2.12 on 2026-03-06 13:01

import django.db.models.deletion
import packages.framework.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("alias", models.CharField(max_length=255, verbose_name="Алиас")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("file", packages.framework.fields.S3PrivateFileField(upload_to="models/")),
                (
                    "subset",
                    models.CharField(
                        choices=[
                            ("classification", "Классификация"),
                            ("segmentation", "Сегментация"),
                            ("detection", "Обнаружение"),
                        ],
                        max_length=32,
                        verbose_name="Задача",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[("tensorflow", "Tensorflow"), ("pytorch", "Pytorch"), ("ultralytics", "Ultralytics")],
                        max_length=32,
                        verbose_name="Фреймворк",
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("deeplabv3", "deeplabv3"),
                            ("unet", "unet"),
                            ("yolo", "yolo"),
                            ("fpn", "fpn"),
                            ("mask_rcnn", "mask_rcnn"),
                        ],
                        max_length=32,
                        verbose_name="Архитектура",
                    ),
                ),
                (
                    "backbone",
                    models.CharField(
                        choices=[("resnet50", "resnet50"), ("resnet101", "resnet101"), ("resnet152", "resnet152")],
                        max_length=32,
                        verbose_name="Backbone",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Готова"),
                            ("deployed", "Развернута"),
                            ("training", "Обучается"),
                            ("archived", "Архив"),
                        ],
                        default="ready",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="TrainingConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "lr_scheduler",
                    models.CharField(
                        choices=[
                            ("StepLR", "StepLR"),
                            ("ExponentialLR", "ExponentialLR"),
                            ("ReduceLROnPlateau", "ReduceLROnPlateau"),
                            ("CosineAnnealingLR", "CosineAnnealingLR"),
                            ("CosineAnnealingWarmRestarts", "CosineAnnealingWarmRestarts"),
                        ],
                        default="ReduceLROnPlateau",
                        max_length=32,
                        verbose_name="Схема обучения",
                    ),
                ),
                (
                    "optimizer",
                    models.CharField(
                        choices=[("adam", "Adam"), ("adamw", "AdamW"), ("sgd", "SGD"), ("rmsprop", "RMSprop")],
                        default="adam",
                        max_length=32,
                        verbose_name="Оптимизатор",
                    ),
                ),
                (
                    "loss_function",
                    models.CharField(
                        choices=[
                            ("BCE", "BCE"),
                            ("BCEWithLogits", "BCEWithLogits"),
                            ("CrossEntropy", "CrossEntropy"),
                            ("MSE", "MSE"),
                        ],
                        default="BCE",
                        max_length=32,
                        verbose_name="Функция потерь",
                    ),
                ),
                ("epochs", models.IntegerField(default=20, verbose_name="Эпох")),
                ("early_stopping_patience", models.IntegerField(default=5, verbose_name="Патейнс")),
                ("train_batch_size", models.IntegerField(default=4, verbose_name="Размер батча")),
                ("valid_batch_size", models.IntegerField(default=2, verbose_name="Размер валидационного батча")),
                ("valid_ratio", models.FloatField(default=0.2, verbose_name="Размер валидационного набора")),
                ("test_ratio", models.FloatField(default=0.1, verbose_name="Размер тестового набора")),
                ("learning_rate", models.FloatField(default=0.0001, verbose_name="Скорость обучения")),
                ("image_width", models.IntegerField(default=512, verbose_name="Ширина изображения")),
                ("image_height", models.IntegerField(default=512, verbose_name="Высота изображения")),
                ("seed", models.IntegerField(default=42, verbose_name="Сид")),
                ("use_flip", models.BooleanField(default=False, verbose_name="Использовать поворот")),
                ("rotation_degrees", models.IntegerField(default=0, verbose_name="Поворот")),
                ("hsv_v", models.IntegerField(default=0, verbose_name="Яркость")),
                ("hsv_s", models.IntegerField(default=0, verbose_name="Насыщенность")),
                ("hsv_h", models.IntegerField(default=0, verbose_name="Оттенок")),
            ],
            options={
                "verbose_name": "Конфигурация обучения модели",
                "verbose_name_plural": "Конфигурации обучения моделей",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="training", to="training.model"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обучение модели",
                "verbose_name_plural": "Обучение моделей",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="datasets.dataset")),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="training.training"
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор данных для обучения модели",
                "verbose_name_plural": "Наборы данных для обучения моделей",
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("queued", "В очереди"),
                            ("running", "Обучение"),
                            ("validating", "Валидация"),
                            ("finished", "Завершено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("current_epoch", models.IntegerField(default=0)),
                ("train_loss", models.FloatField(blank=True, null=True)),
                ("val_loss", models.FloatField(blank=True, null=True)),
                ("test_loss", models.FloatField(blank=True, null=True)),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                ("finished_date", models.DateTimeField(blank=True, null=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="training.training"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск обучения модели",
                "verbose_name_plural": "Запуск обучения моделей",
                "ordering": ("-created_date",),
            },
        ),
    ]
