# Generated by Django 5.2.11 on 2026-02-20 11:46

from django.db import migrations, models

import packages.framework.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("alias", models.CharField(max_length=255, verbose_name="Алиас")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("file", packages.framework.fields.S3PrivateFileField(upload_to="models/")),
                (
                    "subset",
                    models.CharField(
                        choices=[
                            ("classification", "Классификация"),
                            ("segmentation", "Сегментация"),
                            ("detection", "Обнаружение"),
                        ],
                        max_length=32,
                        verbose_name="Задача",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[("tensorflow", "Tensorflow"), ("pytorch", "Pytorch"), ("ultralytics", "Ultralytics")],
                        max_length=32,
                        verbose_name="Фреймворк",
                    ),
                ),
                ("deployed", models.BooleanField(default=False, verbose_name="Развернута")),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
                "ordering": ("-created_date",),
            },
        ),
    ]
