# Generated by Django 5.2.12 on 2026-03-06 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingconfig",
            name="training",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="config", to="training.training"
            ),
        ),
        migrations.AlterField(
            model_name="trainingconfig",
            name="loss_function",
            field=models.CharField(
                choices=[
                    ("BCE", "BCE"),
                    ("DICE", "DICE Loss"),
                    ("BCEWithLogits", "BCEWithLogits"),
                    ("CrossEntropy", "CrossEntropy"),
                    ("BinaryCrossEntropy", "Binary Cross-Entropy"),
                    ("MSE", "MSE"),
                ],
                default="BCE",
                max_length=32,
                verbose_name="Функция потерь",
            ),
        ),
    ]
