# Generated by Django 5.2.12 on 2026-03-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_trainingconfig_training_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingconfig",
            name="in_channels",
            field=models.IntegerField(default=3, verbose_name="Количество каналов входного изображения"),
        ),
        migrations.AlterField(
            model_name="model",
            name="architecture",
            field=models.CharField(
                choices=[
                    ("deeplabv3", "deeplabv3"),
                    ("unet", "unet"),
                    ("yolo", "yolo"),
                    ("fpn", "fpn"),
                    ("mask_rcnn", "mask_rcnn"),
                    ("vision_net", "vision_net"),
                ],
                max_length=32,
                verbose_name="Архитектура",
            ),
        ),
    ]
