# Generated by Django 5.2.12 on 2026-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_trainingconfig_in_channels_alter_model_architecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrun",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="f1_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="iou",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="precision",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="recall",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
