# Generated by Django 5.2.12 on 2026-05-01 18:17

import packages.framework.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_trainingrun_accuracy_trainingrun_f1_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="file_config",
            field=packages.framework.fields.S3PrivateFileField(
                blank=True, null=True, upload_to="models/", verbose_name="Конфигурация модели"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="file",
            field=packages.framework.fields.S3PrivateFileField(upload_to="models/", verbose_name="Файл модели"),
        ),
    ]
